version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - mongo.env
  app:
    build: ./
    container_name: todo-app
    ports:
      - "3005:3005"
    env_file:
      - app.env